### PR TITLE
Fix dim and copy_dim methods in SampleForecast

### PR DESCRIPTION
**Pull request by lostella**
*Issue #, if available:* solves #332 

*Description of changes:* This PR aligns the `dim` and `copy_dim` methods of `SampleForecast` to the samples tensor layout currently produced by e.g. SimpleFeedForwardEstimator and DeepAREstimator. *Note:* this only affects the multivariate case, so for example when `MultivariateGaussianOutput` is used.

Bonus: some rephrasing in docstrings.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-366/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-366/1/index.html

**Comment by szha** [comment]
Job PR-366/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-366/2/index.html

**Comment by szha** [comment]
Job PR-366/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-366/3/index.html

**Comment by szha** [comment]
Job PR-366/4 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-366/4/index.html

**Comment by lostella** [comment]
This PR raises the question: what is the right layout for tensors in forcasts? Should it be (N)CT or (N)TC? Putting the N dimension aside (this could be seen as the batch dimension, or the samples dimension), I see the following pros/cons:

Advantages of TC:
* This is the same layout that is used in distributions, where the C (covariate) axis is the last one. That means that if you're given a `MultivariateGaussian` distribution (apparently constructed with `mu` and `Sigma` having TC and TCC layout respectively), computing the likelihood of a TC observation is immediate, while for a CT axis it requires a transposition.
* The position of the T axis is independent of whether the C axis is there or not. This can make code simpler in a few places I believe.

Advantages of CT:
* It's the way data is ingested currently, and forecast tensors are interpreted for plotting/scoring (before the present PR).
* It's the layout for time-dependent features in [SageMaker's DeepAR](https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html#deepar-inputoutput)

**Comment by szha** [comment]
Job PR-366/5 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-366/5/index.html

**Pull request merged**
