### PR TITLE
Speed up multivariate evaluator by 10x

### PR DESCRIPTION
**Pull request by kashif**
set super's `num_workers=None` since we loop over each dimension to calculate the metrics and thus multiple workers only slow it down

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lostella** [comment]
Looks good to me @kashif! Maybe though it's better to re-expose the setting in the constructor? I can imagine multiprocessing to help in case one has a collection of several multi-dimensional series. What do you think? Thought defaulting it to `None` probably makes sense

**Comment by kashif** [comment]
sure I can do that... let me add it thanks!

**Comment by kashif** [comment]
@lostella done. Can you kindly have a look? Thanks!

**Review by lostella — APPROVED** [review]
🚀

**Pull request merged**
