### PR TITLE
Fix: torch DeepAR observed indicator in multivariate case

### PR DESCRIPTION
**Pull request by kashif**
*Issue #, if available:*

*Description of changes:*
pytorch min return min and min_indicies so only use the min

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by lostella** [comment]
Then I guess the first sentence and example in the docs is wrong? https://pytorch.org/docs/stable/generated/torch.min.html#torch.min

**Comment by lostella** [comment]
Oh I see, it returns a tuple if `dim` is provided? That’s a bit confusing…

**Comment by kashif** [comment]
right... but this code block is never used since its univariate emission model...

**Review by lostella — APPROVED** [review]
🚀 thanks!

**Pull request merged**
