### PR TITLE
Recipe synthetic data genration small refactoring

### PR DESCRIPTION
**Pull request by jgasthaus**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-327/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-327/1/index.html

**Comment by szha** [comment]
Job PR-327/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-327/2/index.html

**Comment by lostella** [comment]
Looks like mypy is complaining now. Check in `requirements/requirements-setup.txt` which versions of black and mypy should be used.

```
black==19.3b0
mypy==0.630
```

**Comment by szha** [comment]
Job PR-327/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-327/3/index.html

**Comment by szha** [comment]
Job PR-327/5 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-327/5/index.html

**Pull request merged**
