### PR TITLE
fix artificial dataset bug

### PR DESCRIPTION
**Pull request by benidis**
Fix issue #82 

The hour and minute random values were out of bound since the `random.Random.randint(low, high)` gives samples with the limits inclusive (`numpy` does not). 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-83/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-83/1/index.html

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/gluon-ts/pull/83?src=pr&el=h1) Report
> Merging [#83](https://codecov.io/gh/awslabs/gluon-ts/pull/83?src=pr&el=desc) into [master](https://codecov.io/gh/awslabs/gluon-ts/commit/2de36e034e1829c9f8eda573d95f6a5cd4773a90?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `0%`.


[Impacted file tree graph](https://codecov.io/gh/awslabs/gluon-ts/pull/83?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #83   +/-   ##
=======================================
  Coverage   78.61%   78.61%           
=======================================
  Files         110      110           
  Lines        6279     6279           
=======================================
  Hits         4936     4936           
  Misses       1343     1343
```

| [Impacted Files](https://codecov.io/gh/awslabs/gluon-ts/pull/83?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/gluonts/distribution/binned.py](https://codecov.io/gh/awslabs/gluon-ts/pull/83/diff?src=pr&el=tree#diff-c3JjL2dsdW9udHMvZGlzdHJpYnV0aW9uL2Jpbm5lZC5weQ==) | `94.87% <ø> (ø)` | :arrow_up: |
| [src/gluonts/dataset/artificial/\_base.py](https://codecov.io/gh/awslabs/gluon-ts/pull/83/diff?src=pr&el=tree#diff-c3JjL2dsdW9udHMvZGF0YXNldC9hcnRpZmljaWFsL19iYXNlLnB5) | `32.16% <0%> (ø)` | :arrow_up: |

**Comment by szha** [comment]
Job PR-83/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-83/2/index.html

**Comment by szha** [comment]
Job PR-83/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-83/3/index.html

**Pull request merged**
