### PR TITLE
Use miniver for version resolution.

### PR DESCRIPTION
**Pull request by jaheba**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaheba** [comment]
This uses https://github.com/jbweston/miniver to resolve dependencies based on tags.

**Comment by jaheba** [comment]
Hmm, how should we handle the license headers? Should we still copy our header in the miniver files?

**Comment by lostella** [comment]
> Hmm, how should we handle the license headers? Should we still copy our header in the miniver files?

One would need to check what the license for miniver says about that

**Comment by jaheba** [comment]
https://github.com/jbweston/miniver/blob/master/LICENSE

Looks like we can do whatever we want :)

**Comment by jaheba** [comment]
This seems to work now. If I run `python setup.py build`, the contents of `gluonts/_static_version.py` is replaced.

**Review by lostella — APPROVED** [review]

**Pull request merged**
