### PR TITLE
small table formatting and script fix

### PR DESCRIPTION
**Pull request by geoalgo**
*Description of changes:*

small table formatting and script fix.

add missing evaluation files.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-84/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-84/1/index.html

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/gluon-ts/pull/84?src=pr&el=h1) Report
> Merging [#84](https://codecov.io/gh/awslabs/gluon-ts/pull/84?src=pr&el=desc) into [master](https://codecov.io/gh/awslabs/gluon-ts/commit/d7e73ec52cb49a52175e51e50ac1f30ed00f774c?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.


[Impacted file tree graph](https://codecov.io/gh/awslabs/gluon-ts/pull/84?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #84   +/-   ##
=======================================
  Coverage   78.63%   78.63%           
=======================================
  Files         110      110           
  Lines        6282     6282           
=======================================
  Hits         4940     4940           
  Misses       1342     1342
```

**Comment by szha** [comment]
Job PR-84/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-84/2/index.html

**Comment by szha** [comment]
Job PR-84/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-84/3/index.html

**Pull request merged**
