### PR TITLE
remove flake8 from githook

### PR DESCRIPTION
**Pull request by geoalgo**
*Description of changes:*
remove flake8 from githook

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lostella** [comment]
Should this file be checked in at all? Maybe not, and we should be modifying dev_setup.sh instead

**Comment by szha** [comment]
Job PR-109/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-109/1/index.html

**Comment by geoalgo** [comment]
> Should this file be checked in at all? Maybe not, and we should be modifying dev_setup.sh instead

Currently, the developer instructions are async as a hook with flake8 is added and it should not. 
I propose to first do this (removing flake8) and then revisit the dev_setup.sh if this is needed.

**Comment by lostella** [comment]
> Currently, the developer instructions are async as a hook with flake8 is added and it should not.
> I propose to first do this (removing flake8) and then revisit the dev_setup.sh if this is needed.

Sorry, got confused :-)

**Comment by szha** [comment]
Job PR-109/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-109/2/index.html

**Comment by szha** [comment]
Job PR-109/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-109/3/index.html

**Pull request merged**
