### PR TITLE
Merges for v0.6.5

### PR DESCRIPTION
**Pull request by lostella**
* Fix serde for np.dtype. (#1299)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by Schmedu — APPROVED** [review]

**Comment by kashif** [comment]
I would appreciate all but the last couple of breaking changes in a release... then I can make a new cut of pytorch-ts which depends on gluon-ts. Else I would need to also go over and update my estimators. Any idea what you plan to include here?

**Comment by lostella** [comment]
@kashif we only include bug fixes in bugfix releases (no new features).

I assume you are referring to #1256? Do you have any concern about that?

**Comment by lostella** [comment]
(This particular backport is rather urgent)

**Comment by kashif** [comment]
No concern... just didn’t get around to integrating it.

**Pull request merged**
