### PR TITLE
fixed taxi dataset cardinality

### PR DESCRIPTION
**Pull request by kashif**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mbohlkeschneider** [comment]
Thank you for catching this! Changing the `cardinality` here will not do the trick, though, the data will need to be reprocessed an uploaded in the[ release fork](https://github.com/mbohlkeschneider/gluon-ts/tree/mv_release/src/gluonts).

**Comment by kashif** [comment]
thanks @mbohlkeschneider can you also see the issue #554 I am seeing some strangeness in the test splits and its not making sense to me...

**Comment by mbohlkeschneider** [comment]
> thanks @mbohlkeschneider can you also see the issue #554 I am seeing some strangeness in the test splits and its not making sense to me...

I'm writing a response to #554 right now. The test splits are intended this way, which will hopefully be clear in the answer to #554

**Comment by kashif** [comment]
@mbohlkeschneider a quick question, in response to your answers, do you still need to reprocess this dataset? Thank you for any insight!!

**Comment by mbohlkeschneider** [comment]
> @mbohlkeschneider a quick question, in response to your answers, do you still need to reprocess this dataset? Thank you for any insight!!

Hi @kashif,

I did not have time to look into this yet. I'll ping you once I have an update!

**Comment by kashif** [comment]
Thanks!

**Pull request merged**
