### PR TITLE
Merges for v0.7.4

### PR DESCRIPTION
**Pull request by Schmedu**
Merge commits:
- Fix Settings._inject to check if it can provide the value. (#1501)
- Fix indentation (#1500)
- Fix anomaly detection example (#1515)
- Add constant dummy time features to TFT for yearly data (#1518)

### CODE REVIEW

**Comment by jaheba** [comment]
```
>       n_windows_per_time_series = self.max_n_datapts // n_time_series
E       ZeroDivisionError: integer division or modulo by zero
```

What's going on there?

**Comment by lostella** [comment]
> What's going on there?

Where did that show up?

**Comment by Schmedu** [comment]
> > What's going on there?
> 
> Where did that show up?

Windows 3.7 in `test\model\rotbaum\test_rotbaum_smoke.py`. See here:

```
________________________ test_rotbaum_smoke[datasets2] ________________________

datasets = (<gluonts.dataset.common.ListDataset object at 0x000001E672D6F288>, <gluonts.dataset.common.ListDataset object at 0x000001E672D6F448>)

    @pytest.mark.parametrize(
        "datasets",
        [
            # No features
            make_dummy_datasets_with_features(),
            # Single static categorical feature
            make_dummy_datasets_with_features(cardinality=[5]),
            # Multiple static categorical features
            make_dummy_datasets_with_features(cardinality=[3, 10, 42]),
            # Multiple static categorical features
            make_dummy_datasets_with_features(cardinality=[3, 10, 42]),
            # Single dynamic real feature
            make_dummy_datasets_with_features(num_feat_dynamic_real=1),
            # Multiple dynamic real feature
            make_dummy_datasets_with_features(num_feat_dynamic_real=3),
            # Multiple dynamic real feature
            make_dummy_datasets_with_features(num_feat_dynamic_real=3),
            # Both static categorical and dynamic real features
            make_dummy_datasets_with_features(
                cardinality=[3, 10, 42], num_feat_dynamic_real=3
            ),
            # Both static categorical and dynamic real features
            make_dummy_datasets_with_features(
                cardinality=[3, 10, 42], num_feat_dynamic_real=3
            ),
        ],
    )
    def test_rotbaum_smoke(datasets):
        dataset_train, dataset_test = datasets
        hps = {
            "freq": "D",
            "prediction_length": 3,
            "context_length": 3,
        }
        estimator = TreeEstimator.from_inputs(dataset_train, **hps)

>       predictor = estimator.train(dataset_train)

test\model\rotbaum\test_rotbaum_smoke.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src\gluonts\model\rotbaum\_estimator.py:43: in train
    return self.predictor.train(training_data)
src\gluonts\model\rotbaum\_predictor.py:179: in train
    ts_list=list(training_data), change_internal_variables=True
src\gluonts\model\rotbaum\_preprocess.py:215: in preprocess_from_list
    self.num_samples = self.get_num_samples(ts_list)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ecast_horizon=3, max_n_datapts=1000000, n_ignore_last=0, num_samples=-1, stratify_targets=False)
ts_list = [{'feat_static_cat': array([ 2,  1, 22]), 'source': SourceContext(source='list_data', row=0), 'start': Timestamp('2018...a', row=4), 'start': Timestamp('2018-01-01 00:00:00', freq='D'), 'target': array([0., 0., 0., 0., 0.], dtype=float32)}]

    def get_num_samples(self, ts_list) -> int:
        """
        Outputs a reasonable choice for number of windows to sample from
        each time series at training time.
        """
        n_time_series = sum(
            [
                len(time_series["target"])
                - self.context_window_size
                - self.forecast_horizon
                >= 0
                for time_series in ts_list
            ]
        )
        max_size_ts = max(
            [len(time_series["target"]) for time_series in ts_list]
        )
>       n_windows_per_time_series = self.max_n_datapts // n_time_series
E       ZeroDivisionError: integer division or modulo by zero

src\gluonts\model\rotbaum\_preprocess.py:257: ZeroDivisionError
---------------------------- Captured stderr setup ----------------------------
DEBUG:root:np/mx/python random seeds are set to 476683422, use MXNET_TEST_SEED=476683422 to reproduce.
----------------------------- Captured log setup ------------------------------
DEBUG    root:conftest.py:184 np/mx/python random seeds are set to 476683422, use MXNET_TEST_SEED=476683422 to reproduce.
---------------------------- Captured stderr call -----------------------------
INFO:gluonts.model.rotbaum._predictor:If using the Evaluator class with a TreePredictor, set num_workers=0.
------------------------------ Captured log call ------------------------------
INFO     gluonts.model.rotbaum._predictor:_predictor.py:170 If using the Evaluator class with a TreePredictor, set num_workers=0.
-------------------------- Captured stderr teardown ---------------------------
INFO:root:np/mx/python random seeds are set to 476683422, use MXNET_TEST_SEED=476683422 to reproduce.
---------------------------- Captured log teardown ----------------------------
INFO     root:conftest.py:190 np/mx/python random seeds are set to 476683422, use MXNET_TEST_SEED=476683422 to reproduce.
```

Sorry, I restarted it to see if it reappears, but I saved all logs.

**Comment by lostella** [comment]
@Schmedu I see, thanks. So it seems to be a flaky test?

**Review by lostella — APPROVED** [review]

**Review by jaheba — APPROVED** [review]

**Comment by Schmedu** [comment]
> @Schmedu I see, thanks. So it seems to be a flaky test?

Yep, seems so. I'll create a new pr and add the decorator

**Pull request merged**
