### PR TITLE
Fix dummy estimator

### PR DESCRIPTION
**Pull request by canerturkmen**
*Issue #, if available:*

*Description of changes:*

It appears the `DummyEstimator.train` still expected `validation_dataset` which conflicts with `Estimator` and broke inheriting dummy classes if `validation_data` was passed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by jaheba** [comment]
Is the failing notebook unrelated?

**Comment by canerturkmen** [comment]
> Is the failing notebook unrelated?

I believe so. I can't see why that would break.

**Comment by canerturkmen** [comment]
Yes looks like the pytorch-lightning version got bumped 

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.6/750.6 MB 1.8 MB/s eta 0:00:00

Collecting pytorch-lightning~=1.5

Downloading pytorch_lightning-1.6.0-py3-none-any.whl (582 kB)
```

Vs previous passing CI
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.6/750.6 MB 1.3 MB/s eta 0:00:00

Collecting pytorch-lightning~=1.5

Downloading pytorch_lightning-1.5.10-py3-none-any.whl (527 kB)
```

**Review by lostella — APPROVED** [review]
Thanks for spotting this!

**Pull request merged**
