### PR TITLE
switched to rollforward

### PR DESCRIPTION
**Pull request by AaronSpieler**
Timestamps will now be aligned using the rollforward method instead of rollback method.
Additionally fixed incorrect comment.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaheba** [comment]
Fixes #279

**Comment by lostella** [comment]
@AaronSpieler some tests are failing: probably they need to be updated to reflect the change?

You can check which tests are failing by clicking on the build details here in the PR, or by running `pytest` locally

**Comment by szha** [comment]
Job PR-328/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-328/2/index.html

**Comment by szha** [comment]
Job PR-328/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-328/3/index.html

**Pull request merged**
