### PR TITLE
Add code for multivariate attack paper

### PR DESCRIPTION
**Pull request by Linbo-Liu**
*Issue #, if available:*

*Description of changes:*
Add the code for the paper Robust Multivariate Time-Series Forecasting: Adversarial Attacks and Defense Mechanisms.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by jaheba** [comment]
Hi @Linbo-Liu,

it looks like you are including all of GluonTS again in your PR. Can you only add code that you are providing?

**Comment by Linbo-Liu** [comment]
> Hi @Linbo-Liu,
> 
> it looks like you are including all of GluonTS again in your PR. Can you only add code that you are providing?

Hi @jaheba,

The GluonTS package is modified. In order to successfully run the code, I have to include them here.

**Comment by jaheba** [comment]
Then let's work on adding the changes that you need. But adding everything again is not feasible for us.

**Comment by Linbo-Liu** [comment]
I have removed repeated files.

**Comment by lostella** [comment]
@Linbo-Liu style checks are failing, make sure to:
- pull the latest changes (changes from `dev` were merged into this one)
- have the latest `black` installed (`pip install -U black`)
- run `black src test`
- commit and push the changes that `black` applies

**Review by lostella — APPROVED** [review]
Thanks @Linbo-Liu!

**Pull request merged**
