### PR TITLE
Training History

### PR DESCRIPTION
**Pull request by PascalIversen**
*Issue*
#1124

*Description of changes:*
I think it should be possible for users to access the training history to monitor overfitting. This is a non breaking way to do that, however I am not sure if the predictor should own the history.

```python
from gluonts.dataset.repository.datasets import get_dataset
from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator
from gluonts.model.deepar import DeepAREstimator
from gluonts.mx.trainer import Trainer
import random

dataset = get_dataset("m4_hourly", regenerate=True)

estimator = SimpleFeedForwardEstimator(
    num_hidden_dimensions = [20, 20],
    prediction_length=dataset.metadata.prediction_length,
    context_length=dataset.metadata.prediction_length*8,
    freq=dataset.metadata.freq,
    trainer=Trainer(epochs=2, learning_rate_decay_factor=0.99, patience=100)
)
n_time_series = len(dataset.train)
n_train_time_series = int(n_time_series*0.5)
dataset_train = list(dataset.train)
random.shuffle(dataset_train)
train_set = dataset_train[:n_train_time_series]
eval_set = dataset_train[n_train_time_series:]

predictor = estimator.train(train_set, validation_data=eval_set)

predictor.training_history

{'training_loss': [5.8661989498138425,
  5.025108561515808,
  4.730559797286987,
  4.819148554801941,
  4.586751465797424,
  4.538518929481507,
  4.649438915252685,
  4.6237060785293576,
  4.435682978630066,
  4.367659435272217],
 'validation_loss': [5.418155691011356,
  4.712160367232102,
  4.557879279641544,
  4.504928608231133,
  4.594020612849746,
  4.695075879778181,
  4.568878847977211,
  4.483525435890307,
  4.307454805116396,
  4.457428598403931]}
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by PascalIversen** [comment]
Closing, as this could be done with #1121

**Comment by nalexus** [comment]
Hey @PascalIversen !
May you pinpoint any info/tutorial on whether training history can be accessed and how ? 
Sorry, but I couldn't find this via linked issues.

**Comment by lostella** [comment]
@nalexus we're reworking the website so that tutorial are better exposed there, but in the meantime you can find a short tutorial [here](https://github.com/awslabs/gluon-ts/blob/master/docs/tutorials/advanced_topics/trainer_callbacks.md) containing an example of that

**Comment by nalexus** [comment]
@lostella thanks!

**Pull request closed without merging**
