### PR TITLE
Update codeql.yml

### PR DESCRIPTION
**Pull request by kashif**
*Issue #, if available:*
Fix deprecation warnings in codeql

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by lostella** [comment]
Is this related to this? https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

**Comment by kashif** [comment]
@lostella  yes exactly

**Comment by jaheba** [comment]
I guess we just merge this?

**Comment by kashif** [comment]
i believe so... just one less thing to worry about i hope!

**Review by jaheba — APPROVED** [review]

**Pull request merged**
