### PR TITLE
Update website template, clean up homepage and tutorials

### PR DESCRIPTION
**Pull request by lostella**
*Description of changes:*

Preview at: https://ts.gluon.ai/experimental/index.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by jaheba** [comment]
Can we preview the changes somewhere?

**Comment by lostella** [comment]
> Can we preview the changes somewhere?

Added link in the OP. It's currently not exactly what it looks like (cloudfront cache needs to update I guess): missing Gluon logo on top left corner, missing one tutorial, possibly other small changes

**Comment by lostella** [comment]
Yes, I had forgotten about generating the API docs and pushed to S3 too early, it should be coming

**Comment by babaniyi** [comment]
@lostella Will you include the tutorials for pandas dataframe support proposed [here](https://github.com/awslabs/gluon-ts/pull/1935#event-6702750922)

**Comment by lostella** [comment]
@babaniyi yes, we have work in progress to add those

**Pull request merged**
