### PR TITLE
Use static categorical feature for evaluating m4 datasets

### PR DESCRIPTION
**Pull request by rshyamsundar**
#376 

We currently do not use categorical feature in the evaluation of m4 datasets although this is present in the dataset. This often results in large error for `m4_hourly`. This PR adds cat feature  for the m4 evaluation. 

I ran deepar model with and without categorical feature. For `m4_hourly` there is a clear improvement. On other datasets using cat feature is slightly better for almost all datasets in terms of  `RMSE`, `mean_wQunatileLoss`, `MASE`. On the other metrics it is mixed although I think using cat in principle should always give better results; need to check the impact of `embedding_dim` on the performance.

**Without cat feature**

|dataset        |estimator         |RMSE  |mean_wQuantileLoss      |MASE|     sMAPE       |MSIS
| --- | --- | --- | ---  | --- | --- | --- | 
|     m4_hourly  |DeepAREstimator  |6287.739733            |0.106407  |1.783540  |0.131712  |26.874568
|      m4_daily  |DeepAREstimator   |669.159914            |0.025856  |4.120823  |0.038060  |54.246199
|     m4_weekly  |DeepAREstimator   |668.698652            |0.051018  |2.848970  |0.084453  |26.471953
|    m4_monthly  |DeepAREstimator  |1422.962951            |0.118168  |1.196579  |0.140440  |26.074230
|  m4_quarterly  |DeepAREstimator  |1397.590109            |0.086418  |1.299676  |0.106761  |16.885508
|     m4_yearly  |DeepAREstimator  |1802.114059            |0.121546  |3.638369  |0.145967  |59.942453

**With cat feature**

| dataset        | estimator         | RMSE  | mean_wQuantileLoss      | MASE     | sMAPE       | MSIS
| --- | --- | --- | ---  | --- | --- | --- | 
|     m4_hourly  |DeepAREstimator |  2224.828709           |  0.043838 |  1.388138 |  0.125006 |  23.352866
|      m4_daily  |DeepAREstimator  |  630.971563           | 0.024090  | 3.570393  | 0.033416  | 45.372105
|     m4_weekly  |DeepAREstimator  | 671.174265            | 0.050066  | 2.894249  | 0.085407  | 35.433631
|    m4_monthly  |DeepAREstimator  |1404.456407            | 0.113999  | 1.113356  | 0.140272  | 22.465503
|  m4_quarterly  |DeepAREstimator  | 1407.398593           | 0.086242  | 1.434469  | 0.111112  | 18.267942
|     m4_yearly  | DeepAREstimator | 1975.966961           | 0.136738  | 4.237890  | 0.165475  | 72.581687

### CODE REVIEW

**Comment by gjmulder** [comment]
Looking at a recent download of the M4 hourly data I see that the cardinality for each is set to the number of time series:

```
$ wc -l ./train/data.json 
414 ./train/data.json
$ cat metadata.json 
{"freq": "H", "prediction_length": 48, "feat_static_cat": [{"name": "feat_static_cat", "cardinality": "414"}]}
$ awk '{print $NF}' ./train/data.json | tail
[404]}
[405]}
[406]}
[407]}
[408]}
[409]}
[410]}
[411]}
[412]}
[413]}
```
I would have thought that this static feature was the category (e.g. Demographic, Finance, Industry, Macro, Micro, Other) ?

**Comment by mharvan** [comment]
@rshyamsundar I am also confused: M4 hourly data category is always "Other". Why would adding this information improve forecasts?

$ grep Hourly M4-info.csv | wc -l
414                                                                                          
$ grep Hourly M4-info.csv | grep -v Other | wc -l
0

**Comment by rshyamsundar** [comment]
The "Other" category is the categorization provided externally by m4 competition. But in gluonts one categorical feature is explicitly added while creating a gluots compatible dataset from the raw data; this cat feature is just an index of the item in the raw dataset.

Look [here](https://github.com/awslabs/gluon-ts/blob/481fc5fdd09abad012cf6398e06bc6be8b1de197/src/gluonts/dataset/repository/_m4.py#L75) to see where this cat feature is created for m4 datasets.

**Comment by gjmulder** [comment]
Therefore there are two potential categorical features available for the M4 data. The first of which GluonTS looks to plan to use w.r.t. this issue:

1. The index of the time series, which may help the global model with predicting a specific time series
2. The M4-specific domain category of the time series from [M4-info.csv](https://github.com/M4Competition/M4-methods/blob/master/Dataset/M4-info.csv), which were used in the winning M4 entry by Uber

I'm now using both :-)

In addition, there are (somewhat ambiguous) start dates and times also provided in [M4-info.csv](https://github.com/M4Competition/M4-methods/blob/master/Dataset/M4-info.csv) which don't seem to be present in the GluonTS version of the M4 data set. As GluonTS looks to automatically generate features from the data set frequency metadata, the start dates for the M4 data are potentially significant for aligning months and days to better model seasonality effects.

**Comment by ASalvail** [comment]
This PR should be reverted as `SimpleFeedForwardEstimator` does not (anymore?) expect a `use_feat_static_cat` parameter.

Or at least, move the extra parameter to the `partial` of the two `deepar`.

**Pull request merged**
