### PR TITLE
Custom scm version handling.

### PR DESCRIPTION
**Pull request by jaheba**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaheba** [comment]
Example:

```
$ python -c "import gluonts; print(gluonts.__version__)"                                                                
dev.custom-scm-version+ga8d6cdd
```

```
$ git tag v0.7.0 
$ python -c "import gluonts; print(gluonts.__version__)"
v0.7.0
```

**Comment by lostella** [comment]
Does this work is the running environment doesn't have `git`? Say, one pip-installs gluon-ts from PyPI, but is not developing it

**Comment by jaheba** [comment]
In that case you should get `"0.0.0-unknown"`.

**Comment by lostella** [comment]
> In that case you should get `"0.0.0-unknown"`.

but you probably want the correct version instead, right?

**Pull request closed without merging**
