### PR TITLE
Add synthetic data generation tutorial

### PR DESCRIPTION
**Pull request by jgasthaus**
*Description of changes:*

Adds a tutorial on synthetic data generation using recipes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lostella** [comment]
The docs build is failing, maybe because this PR depends on #327?

**Comment by jgasthaus** [comment]
> The docs build is failing, maybe because this PR depends on #327?

Yes, probably. Let me try restarting them now that #327 is merged.

**Comment by szha** [comment]
Job PR-356/4 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-356/4/index.html

**Comment by szha** [comment]
Job PR-356/5 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-356/5/index.html

**Pull request merged**
