### PR TITLE
Allow PyTorch 2.0

### PR DESCRIPTION
**Pull request by lostella**
*Description of changes:* Updates requirements file, and test workflow to run on PyTorch 2.0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by lostella** [comment]
The requirement on [CP-Flow](https://github.com/KelvinKan/CP-Flow/tree/package-specific-version) is holding the torch version back in the test workflow, see https://github.com/awslabs/gluonts/actions/runs/4437894021/jobs/7788213888?pr=2724#step:4:422. This happens through:
- https://github.com/awslabs/gluonts/blob/dev/.github/workflows/tests-torch.yml#L30
- https://github.com/awslabs/gluonts/blob/dev/requirements/requirements-extras-cpflows.txt
- https://github.com/KelvinKan/CP-Flow/blob/package-specific-version/requirements.txt#L16

Also holds other stuff back, like Pandas. We need to solve this somehow.

**Comment by melopeo** [comment]
It seems that one test is failing, i.e. `test/ext/statsforecast/test_statsforecast.py::test_model_config`. Can we check it?

**Comment by melopeo** [comment]
The test issue seems to be related to other dependencies, likely nothing to do with this PR.

**Review by melopeo — APPROVED** [review]

**Comment by lostella** [comment]
The failure is related to https://github.com/plotly/dash/issues/2460

**Pull request merged**
