### PR TITLE
Increase number of samples for testing distributions

### PR DESCRIPTION
**Pull request by vafl**
*Description of changes:*

Increase number of samples for testing distributions to make tests more reliable.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-390/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/1/index.html

**Comment by jaheba** [comment]
Could we remove the `flaky` decorator with this?

**Comment by vafl** [comment]
Seems to run through without `flaky`.

**Comment by szha** [comment]
Job PR-390/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/2/index.html

**Comment by szha** [comment]
Job PR-390/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/3/index.html

**Pull request merged**
