### PR TITLE
fix lost freq of pandas timestamp

### LINKED ISSUE #78: Working with Weekly or Montly time series
Hello,

I am having difficulties to work with Weekly and Montly frequency.

When I run this code using Daily frequenct, it works properly, however, if I resample to weekly or montly I get the following error:

`TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'`

Here is my code:

```
from gluonts.dataset.util import to_pandas
from gluonts.trainer import Trainer
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn')
from gluonts.dataset import common
from gluonts.model import deepar
import pandas as pd

!pip install quandl

import quandl

dataset = pd.DataFrame(quandl.get("FRED/DEXBZUS"))

dataset = dataset.resample('M').apply(lambda ser: ser.iloc[-1,])

training_data = common.ListDataset([{"start": dataset.index[0],
                            "target": dataset.Value[:"2017"]}],
                          freq="M")

estimator = deepar.DeepAREstimator(freq="M", prediction_length=40, trainer=Trainer( epochs=5))
predictor = estimator.train(training_data=training_data)

for test_entry, forecast in zip(training_data , predictor.predict(training_data )):
    to_pandas(test_entry)[-60:].plot(linewidth=2)
    forecast.plot(color='g', prediction_intervals=[50.0, 90.0])
plt.grid(which='both')
```

### PR DESCRIPTION
**Pull request by vafl**
*Issue #, if available:*

Fixes #78

*Description of changes:*

Fix lost frequency in pandas timestamp

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-79/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-79/1/index.html

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/gluon-ts/pull/79?src=pr&el=h1) Report
> Merging [#79](https://codecov.io/gh/awslabs/gluon-ts/pull/79?src=pr&el=desc) into [master](https://codecov.io/gh/awslabs/gluon-ts/commit/bf3aa5416c7006cc1ba6cf7d75a8f0e5277acc99?src=pr&el=desc) will **increase** coverage by `<.01%`.
> The diff coverage is `100%`.


[Impacted file tree graph](https://codecov.io/gh/awslabs/gluon-ts/pull/79?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master      #79      +/-   ##
==========================================
+ Coverage    78.6%   78.61%   +<.01%     
==========================================
  Files         110      110              
  Lines        6278     6279       +1     
==========================================
+ Hits         4935     4936       +1     
  Misses       1343     1343
```

| [Impacted Files](https://codecov.io/gh/awslabs/gluon-ts/pull/79?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/gluonts/transform.py](https://codecov.io/gh/awslabs/gluon-ts/pull/79/diff?src=pr&el=tree#diff-c3JjL2dsdW9udHMvdHJhbnNmb3JtLnB5) | `81.49% <100%> (+0.04%)` | :arrow_up: |

**Comment by benidis** [comment]
I reproduced the error downloading the quandl dataset and following the code. I was ready to push the fix and then I saw that Valentin had already fixed it! 

I think it is a pandas bug. 

BTW m4_monthly and m4_weekly do not run for exactly this reason. This may explain a lot about the overall m4 results.

**Comment by vafl** [comment]
@lostella Yes, I suspect it broke in a recent version of pandas. I'll check and perhaps submit an issue.

**Pull request merged**
