### PR TITLE
Fixes for MXNet 1.8

### PR DESCRIPTION
**Pull request by lostella**
*Issue #, if available:* #1374

Tests against mxnet 1.8 cannot be enabled because the pypi package for windows is not available. However this PR passes tests on macos and linux when using mxnet 1.8.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mbohlkeschneider — COMMENTED** [review]
There were issues when doing inference on SageMaker with mxnet 1.7. Does this problem still persist with mxnet 1.8?

**Comment by lostella** [comment]
> There were issues when doing inference on SageMaker with mxnet 1.7. Does this problem still persist with mxnet 1.8?

I'm not sure, we would have to try: this fix only concerns failing tests. What kind of issues are there on SM with 1.7?

**Comment by mbohlkeschneider** [comment]
There wasn't a particular error message. Inference jobs where not running, basically (i.e. running forever).

**Comment by lostella** [comment]
I see, that doesn't sound right. I think the best thing to do is to try out an mxnet 1.8-based container to see whether it was mxnet 1.7 causing the issue. From the tests I ran on mxnet 1.8 for the present PR, everything was green except the one I went fixing

**Review by jaheba — APPROVED** [review]

**Pull request merged**
