### PR TITLE
Fix: remove multiprocessing from `TSFReader`

### PR DESCRIPTION
**Pull request by lostella**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by jaheba** [comment]
I don't think this is a bug.

**Review by jaheba — APPROVED** [review]

**Comment by lostella** [comment]
> I don't think this is a bug.

Well something is not working correctly

**Review by abdulfatir — APPROVED** [review]

**Comment by jaheba** [comment]
Python?

**Comment by lostella** [comment]
> Python?

I guess I don't have a fix for that 😢

**Pull request merged**
