### PR TITLE
docs: fix typos in basic and extended forecasting tutorials

### PR DESCRIPTION
**Pull request by lucasmelin**
*Issue #, if available:*
None

*Description of changes:*
Fix a variety of typos in the basic forecasting and extended forecasting tutorials.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-370/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-370/1/index.html

**Comment by lostella** [comment]
This looks great, thanks a lot for the fixes!

**Comment by szha** [comment]
Job PR-370/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-370/2/index.html

**Comment by lucasmelin** [comment]
@lostella Thanks for the quick review, much appreciated!

**Pull request merged**
