### PR TITLE
Bump up numpy version

### PR DESCRIPTION
**Pull request by mbohlkeschneider**
*Issue #, if available:*
Related to #470 . Bumping up numpy because: 

1. Users ask for it. 
2. We will need the numpy `take_along_axis` operator for the marginal CDF transformation of the Gaussian Copula model that comes in numpy version `1.16)

*Description of changes:*
Bumping up numpy version. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaheba** [comment]
I think the issue is that mxnet has a lower version requirement for numpy and thus pip will complain. Can we wait for mxnet 1.5.2?

**Comment by lostella** [comment]
I think this change is not necessary, since `~=1.14` is equivalent to `>=1.14 and ==1.*`

More here: https://www.python.org/dev/peps/pep-0440/#compatible-release

**Comment by mbohlkeschneider** [comment]
It looks that the builds use numpy 1.14, no (as evidenced here: https://github.com/awslabs/gluon-ts/pull/483/checks?check_run_id=324352451) Thus, they would fail if you would have something with higher dependency?

**Comment by jaheba** [comment]
No, I think it's using 1.16. But it logs an error: https://github.com/awslabs/gluon-ts/pull/483/checks?check_run_id=324352451#step:4:89

**Comment by mbohlkeschneider** [comment]
I guess I don't understand the interactions then. [This build](https://github.com/awslabs/gluon-ts/pull/476/checks?check_run_id=322821447) (without the change) does suggest that it would take numpy `1.14` (unless I'm miskaten again). So it DOES matter?

**Comment by mbohlkeschneider** [comment]
> I think the issue is that mxnet has a lower version requirement for numpy and thus pip will complain. Can we wait for mxnet 1.5.2?

I'd like to have the gaussian copula model merged to mainline until the end of next week for NeurIPS... :-(.

**Comment by mbohlkeschneider** [comment]
I'll monkey patch this for now. I can implement the operator differently by monkey patching, although it will be quite a bit (~5 times) slower than the native numpy operator that comes with numpy `1.16`. We should bump this up as soon as mxnet let us do it...

**Comment by jaheba** [comment]
Maybe we should track issues depending on mxnet 1.5.2?

**Pull request closed without merging**
