### PR TITLE
Add missing value imputation to Seasonal Naive

### PR DESCRIPTION
**Pull request by abdulfatir**
*Issue #, if available:* #2560

*Description of changes:*
This PR adds missing value imputation to `SeasonalNaivePredictor`. Previously, the predictor would return `nan` as forecast if the value at previous season was `nan`. I have set the default imputation strategy to `LastValueImputation` which makes sense in the case of `SeasonalNaivePredictor` but we can change this to something else.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by lostella** [comment]
@abdulfatir I think it makes sense to add some tests for `SeasonalNaivePredictor`. You could add a dedicated test module in `test/model` in the same spirit as https://github.com/awslabs/gluonts/blob/dev/test/model/trivial/test_moving_average.py, or merge the two into a single test module for baseline models.

**Comment by abdulfatir** [comment]
@lostella Sure, I will add the tests.

**Comment by abdulfatir** [comment]
@lostella It looks like that tests that I added are not running on github. Do I need to change something else to make them run?

**Comment by lostella** [comment]
is it not running? where do you see that?

**Comment by abdulfatir** [comment]
[In the logs](https://github.com/awslabs/gluonts/actions/runs/3938533195/jobs/6737337368). I searched for `test_seasonal_naive`.

**Comment by lostella** [comment]
I think that's because we use the `-n2` option from `pytest-xdist` to run tests in parallel over multiple CPUs. In that case the tests are not listed individually by module, but rather displayed in a more compact format like

```
........................................................................ [  2%]
.......................................X................................ [  4%]
ssssssssssssssssssssssss................................................ [  7%]
...................x.......X..................................s.ssssssss [  9%]
sssssssssssssss......................................................... [ 11%]
........................................................................ [ 14%]
.......................X.x..X.....ssss........sss....................... [ 16%]
............................x.X........X..sss..........ssss............. [ 18%]
........................................................................ [ 21%]
```

**Review by lostella — APPROVED** [review]
🚢 it!

**Pull request merged**
