### PR TITLE
Simplify inference tests, fix Binned distribution

### PR DESCRIPTION
**Pull request by lostella**
*Description of changes:*
* The code for inference tests is simplified a bit.
* An assertion is added, to make sure the loss tensor has the expected ("batch") shape during SGD.
* Binned and BinnedOutput are fixed (for example, it is now hybridizable).
* A docstring in the DistributionOutput class is improved.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-57/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-57/1/index.html

**Comment by szha** [comment]
Job PR-57/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-57/2/index.html

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/gluon-ts/pull/57?src=pr&el=h1) Report
> Merging [#57](https://codecov.io/gh/awslabs/gluon-ts/pull/57?src=pr&el=desc) into [master](https://codecov.io/gh/awslabs/gluon-ts/commit/1939cb4769b1b6132081ffcc8f8133fb38cb7ebf?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.


[Impacted file tree graph](https://codecov.io/gh/awslabs/gluon-ts/pull/57?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #57   +/-   ##
=======================================
  Coverage   77.81%   77.81%           
=======================================
  Files         108      108           
  Lines        6189     6189           
=======================================
  Hits         4816     4816           
  Misses       1373     1373
```

**Comment by lostella** [comment]
This requires some further adjustments to shapes, which are in part addressed in #58.
I will also add assertions here, to make sure that shapes are as expected.

**Comment by szha** [comment]
Job PR-57/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-57/3/index.html

**Comment by szha** [comment]
Job PR-57/4 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-57/4/index.html

**Comment by szha** [comment]
Job PR-57/5 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-57/5/index.html

**Pull request merged**
