### PR TITLE
Scale the negative binomial's gamma()

### PR DESCRIPTION
**Pull request by kashif**
For issue #906 

The `theta` param. of Gamma gets scaled by `scale *theta = alpha * mu * scale`. So only need to scale the `mu` . See: https://en.wikipedia.org/wiki/Gamma_distribution#Scaling

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lostella** [comment]
Thanks @kashif, this looks good to me. It would be nice to validate this against some artificial examples, both with small and large scale (eg the snippet in #814). But the example you included in #906 looks already very good

**Comment by kashif** [comment]
```python
data = np.random.negative_binomial(n=10, p=0.9, size=(200,))

data_series = pd.Series(
    data=data,
    index=pd.date_range(
        start='2014-01-05 00:00:00',
        periods=len(data),
        freq='w'
    )
)

dataset = ListDataset(
    data_iter=[
        {
            "start": '2014-01-05 00:00:00',
            "target": list(data)
        }
    ],
    freq="w"
)

estimator = SimpleFeedForwardEstimator(
    freq="w",
    prediction_length=20,
    distr_output=NegativeBinomialOutput(),
    trainer=Trainer(epochs=20, device='cuda'),
)

predictor = estimator.train(dataset)

forecast = next(iter(predictor.predict(dataset)))
data_series.plot()
forecast.plot()
plt.show()
```

download

**Comment by canerturkmen** [comment]
Hi Kashif, Thanks for your contribution and not letting go of this issue. Just to help me understand, I understand #814 led to a degradation. I can't immediately make the connection between how Gamma scaling would apply directly here, although I have some intuition about how it would apply approximately. Perhaps, for very small scales this could still fail, for reasons analogous to the discussion in #814?

**Comment by kashif** [comment]
@canerturkmen ok so the degradation was not due to #814, but my attempt to fix the original scaling issue in the NB output i.e. #718. There i was trying to "fix" the scaling as proposed by the deepAR paper. This I have now come realise is wrong... after looking at the issue again and questioning my assumptions I realized that the proper way of scaling the NB is to sample from a `scale*rate` gamma distribution which then means due to the scaling property of the gamma distribution in the parametrization of gluton-ts we just need to scale the `mu`. I hope that clears up the issue?

**Comment by canerturkmen** [comment]
Yes, this makes sense. Though I'm surprised this didn't drop out of the algebra for #814. Thanks!

**Comment by kashif** [comment]
@canerturkmen I too was / am surprised at that... I'm gonna go through the algebra again but perhaps not around midnight haha :sleeping:

**Pull request merged**
