### PR TITLE
Add --no-dir-entries to zip file creation to prune empty directories

### PR DESCRIPTION
**Pull request by jgasthaus**
*Issue #, if available:*

Addresses #66 

*Description of changes:*

Disable the creating of directory entries in the zip file (which then omits empty directories as a side effect).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-73/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-73/1/index.html

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/gluon-ts/pull/73?src=pr&el=h1) Report
> Merging [#73](https://codecov.io/gh/awslabs/gluon-ts/pull/73?src=pr&el=desc) into [master](https://codecov.io/gh/awslabs/gluon-ts/commit/8ddf21af4d1f8043de287ed2e1326d49c8201989?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.


[Impacted file tree graph](https://codecov.io/gh/awslabs/gluon-ts/pull/73?src=pr&el=tree)

```diff
@@          Coverage Diff           @@
##           master     #73   +/-   ##
======================================
  Coverage    78.6%   78.6%           
======================================
  Files         110     110           
  Lines        6278    6278           
======================================
  Hits         4935    4935           
  Misses       1343    1343
```

**Comment by lostella** [comment]
Now it looks right, thanks!

**Comment by szha** [comment]
Job PR-73/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-73/2/index.html

**Pull request merged**
