### PR TITLE
Remove `.to_timestamp()` to fix interval plotting

### PR DESCRIPTION
**Pull request by abdulfatir**
*Issue #, if available:* #2795

*Description of changes:*
Plotting intervals sometimes do not work due to how pandas plotting interacts with `plt.fill_between`. Using a period index appears to solve the issue, in my experience. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by jaheba** [comment]
Can you check that this looks good using different frequencies? I think I had some problems using `PeriodIndex`.

**Comment by abdulfatir** [comment]
Tested with different frequencies using this script. Works for all.

```py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from gluonts.model.forecast import SampleForecast

freq = ["H", "2H", "T", "2T", "D", "2D", "B", "W", "M", "Y"]

for f in freq:
    print(f)
    sf = SampleForecast(
        samples=np.random.randn(100, 24), start_date=pd.Period("2023", f)
    )
    sf.plot()
    plt.show()

```

**Comment by jaheba** [comment]
Should we backport these fixes? @lostella

**Comment by abdulfatir** [comment]
@jaheba Do you remember the problems you faced with `PeriodIndex` previously? @rshyamsundar was wondering if we can add a test for this somehow.

**Comment by jaheba** [comment]
I think the plot didn't show up right. Not sure how we would be able to test this.

**Review by jaheba — APPROVED** [review]

**Comment by lostella** [comment]
@abdulfatir @jaheba issue #2205 is related to `PeriodIndex` vs `DatetimeIndex`, there's some context there

**Pull request merged**
