### PR TITLE
More operators for synthetic data generation

### PR DESCRIPTION
**Pull request by jgasthaus**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-286/1 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-286/1/index.html

**Comment by lostella** [comment]
Stuff needs to be blackest

**Comment by szha** [comment]
Job PR-286/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-286/2/index.html

**Comment by lostella** [comment]
Looks like some code is outdated (maybe after a rebase?):

```python
==================================== ERRORS ====================================
___________ ERROR collecting test/dataset/artificial/test_recipe.py ____________
ImportError while importing test module '/var/lib/jenkins/workspace/workspace/gluon-ts-cpu-py3/test/dataset/artificial/test_recipe.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/dataset/artificial/test_recipe.py:27: in <module>
    from gluonts.dataset.artificial.recipe import (
E   ImportError: cannot import name 'evaluate_recipe'
_____________ ERROR collecting test/model/test_models_synthetic.py _____________
test/model/test_models_synthetic.py:26: in <module>
    dataset_info, train_ds, test_ds = default_synthetic()
src/gluonts/dataset/artificial/_base.py:779: in default_synthetic
    generated = data.generate()
src/gluonts/dataset/artificial/_base.py:735: in generate
    for x in full_length_data
src/gluonts/dataset/artificial/_base.py:735: in <listcomp>
    for x in full_length_data
src/gluonts/dataset/artificial/_base.py:706: in trim_ts_item_front
    item=x["item"],
E   KeyError: 'item'
```

**Comment by szha** [comment]
Job PR-286/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-286/3/index.html

**Comment by szha** [comment]
Job PR-286/4 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-286/4/index.html

**Comment by vafl** [comment]
Looks good. Black is still complaining about `src/gluonts/dataset/artificial/recipe.py`

**Comment by szha** [comment]
Job PR-286/5 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-286/5/index.html

**Comment by szha** [comment]
Job PR-286/6 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-286/6/index.html

**Pull request merged**
