### PR TITLE
Fixes for Monash Forecasting Repository datasets

### PR DESCRIPTION
**Pull request by borchero**
*Issue #, if available:* n/a

*Description of changes:* This PR implements two minor (yet important) improvements for datasets from the [Monash Forecasting Repository](https://forecastingdata.org).

**1: TSF Reader**

The `TSFReader` currently uses `glide.imap_unordered` to process the individual lines of the downloaded dataset file. As a result, preprocessing pipelines are nondeterministic which causes a problem if a deterministic order of e.g. test time series is required.

This PR continues to use `glide.imap_unordered`, but passes an additional index to the worker function which enables sorting according to this index after all items have been processed. This way, the dataset is generated in the same way on every invocation.

**2: Generated Keys**

Currently, all time series extracted from Monash datasets only have a `target` and `start_timestamp` field. However, some datasets (which are not explicitly made available via GluonTS but could be used by third parties) do not provide start timestamps for the time series. An optional "fallback" start timestamp can now be provided.

Additionally, a unique `item_id` is generated for every time series. This aligns with the other datasets available in GluonTS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by kashif** [comment]
@borchero do you which time seris don't have a `start_date`?

**Comment by borchero** [comment]
@kashif I'm not sure if there's any datasets that are directly available via GluonTS, but this applies to some datasets on [forecastingdata.org](forecastingdata.org). One example is the "Weather" dataset.

**Comment by kashif** [comment]
@borchero awesome, yes that was my question

**Review by jaheba — APPROVED** [review]
Thanks!

**Pull request merged**
