### PR TITLE
Exceptions cleanup.

### PR DESCRIPTION
**Pull request by jaheba**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev setup

### CODE REVIEW

**Comment by jaheba** [comment]
@lostella Any objections?

**Review by lostella — APPROVED** [review]
Looks good to me. Is this still breaking even if you kept the former import path?

**Comment by jaheba** [comment]
Hmm, good question. It's not breaking breaking.

**Comment by lostella** [comment]
@jaheba removed the BREAKING label
@jaheba added the NOT BREAKING BREAKING label

**Pull request merged**
